# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -XX:+EnableDynamicAgentLoading
android.useAndroidX=true
android.builtInKotlin=true
android.newDsl=true
kotlin.code.style=official
android.javaCompile.suppressSourceTargetDeprecationWarning=true
ksp.incremental=true
ksp.incremental.intermodule=true
