package br.com.gazoza.alcoolougasolina.util

const val LAST_ETHANOL = "PrefLastEthanol"
const val LAST_GASOLINE = "PrefLastGasoline"
const val PREF_DEVICE_ID = "PrefDeviceId"
const val PREF_FCM_TOKEN = "PrefFcmToken"
const val PREF_SHARE_LINK = "PrefStoreLink"
const val PREF_HAVE_PLAN = "PrefHavePlan"
const val PREF_APP_NAME = "PrefAppName"
const val PREF_NAME_TO_REMOVE = "PrefNameToRemove"
const val PREF_ADMOB_ID = "PrefAdMobId"
const val PREF_ADMOB_AD_MAIN_ID = "PrefAdMobAdMainId"
const val PREF_ADMOB_INTERSTITIAL_ID = "PrefAdMobInterstitialId"
const val PREF_ADMOB_REMOVE_ADS_ID = "PrefAdMobRemoveAds"
const val PREF_BILL_PLAN_YEAR = "PrefBillPlanYear"
const val PREF_NOTIFICATION_JSON = "PrefNotificationJson"
const val PREF_PLAN_VIDEO_DURATION = "PrefPlanVideoDuration"
const val PREF_PLAN_VIDEO_MILLIS = "PrefPlanVideoMillis"
